services:
  - type: web
    name: vacuum-pump-maintenance
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      chmod +x render_build.sh
      ./render_build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: vacuum-pump-db
          property: connectionString
    # Add a health check to ensure the app is running correctly
    healthCheckPath: /
    # Add automatic database initialization on deploy
    initialDeployHook: python db_init.py

# A PostgreSQL database
databases:
  - name: vacuum-pump-db
    databaseName: vacuum_pump_maintenance
    user: vacuum_pump_user
    plan: free
    # Add ipAllowList to allow connections from the web service
    ipAllowList: []
    # Ensure the database is created before the web service starts
    postProvisionCommands:
      - echo "Database provisioned successfully"
