services:
  - type: web
    name: vacuum-pump-maintenance
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      chmod +x render_build.sh
      ./render_build.sh
    startCommand: gunicorn app:app --log-level debug --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: vacuum-pump-db
          property: connectionString
      - key: SQLALCHEMY_ECHO
        value: "true"
      # Authentication environment variables
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ALLOWED_EMAIL_DOMAINS
        sync: false
      - key: ADMIN_EMAILS
        sync: false
    # Add a health check to ensure the app is running correctly
    healthCheckPath: /
    # Run first_deploy.py to initialize the database on first deployment only
    initialDeployHook: |
      echo "Running first deployment script..."
      python first_deploy.py

# A PostgreSQL database
databases:
  - name: vacuum-pump-db
    databaseName: vacuum_pump_maintenance
    user: vacuum_pump_user
    plan: free
    # Add ipAllowList to allow connections from the web service
    ipAllowList: []
    # Ensure the database is created before the web service starts
    postProvisionCommands:
      - echo "Database provisioned successfully"
    # Prevent database from being deleted on redeploy
    preserveData: true
