services:
  - type: web
    name: vacuum-pump-maintenance
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      chmod +x render_build.sh
      ./render_build.sh
    startCommand: gunicorn app:app --log-level debug --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: SQLALCHEMY_ECHO
        value: "false"
      # Supabase Configuration
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_DB_HOST
        sync: false
      - key: SUPABASE_DB_NAME
        sync: false
      - key: SUPABASE_DB_USER
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: SUPABASE_DB_PORT
        sync: false
      # Authentication environment variables
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ALLOWED_EMAIL_DOMAINS
        sync: false
      - key: ADMIN_EMAILS
        sync: false
    # Add a health check to ensure the app is running correctly
    healthCheckPath: /
    # No need to initialize the database since we're using Supabase
    initialDeployHook: |
      echo "Using Supabase database - no initialization needed"
