services:
  - type: web
    name: vacuum-pump-maintenance
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      chmod +x render_build.sh
      ./render_build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
