services:
  - type: web
    name: vacuum-pump-maintenance
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      chmod +x render_build.sh
      ./render_build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: vacuum-pump-db
          property: connectionString

# A PostgreSQL database
databases:
  - name: vacuum-pump-db
    databaseName: vacuum_pump_maintenance
    user: vacuum_pump_user
    plan: free
